### ISSUE TITLE
Installation instructions seem to not cover KDE

### ISSUE THREAD

**Issue by terr72** [jlu5/icoextract#4]
`pip3 install icoextract` followed by copying `exe-thumbnailer.thumbnailer` into /usr/local/share/thumbnailers/ works fine for me on XFCE and Gnome, however on KDE/Dolphin this doesn't seem to do the trick.

Is there a different approach required or am I doing sth. wrong?

**Comment by jlu5** [comment]
You're right, KDE is an exception because they have their own fairly complete thumbnailing stack. On Debian/Ubuntu for example, the `kio-extras` package installs `/usr/lib/x86_64-linux-gnu/qt5/plugins/windowsexethumbnail.so`, which provides thumbnails for .exe files in Dolphin. (It also includes other thumbnailers for opendocument, djvu, etc.)

**Comment by terr72** [comment]
Actually I had to install icoutils in order to see icons in KDE/Dolphin from EXE files, kio-extras alone wasn't sufficient (stock Kubuntu Focal).
Then I had to realise that icoutils needs about 100-200ms before it switches from the default icon to the actual icon. That's why I thought would be a good idea to switch to the much faster icoextract I'm used to from XFCE/GNOME.

**Comment by jlu5** [comment]
I did a bit more research and it appears that KDE only supports C++ / Qt modules for thumbnailers, and not generic scripts like most file managers. So unfortunately, I don't think it's feasible to add support for KDE since it uses a completely different architecture.

- https://forum.kde.org/viewtopic.php?f=224&t=132463
- https://api.kde.org/frameworks/kio/html/classThumbCreator.html

**Comment by terr72** [comment]
OK, thanks for your efforts!
